// ============================================================
// Centralized App Strings (English)
// Keep all UI text in this single file so Bangla, Hindi,
// and Urdu translations can easily be added later.
// ============================================================

export const strings = {
  common: {
    appName: 'StampUp',
    tagline: 'Digital Stamp Card for Shops & Cafés',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    error: 'Something went wrong. Please try again.',
    networkError: 'No internet connection. Please check your network.',
    retry: 'Retry',
  },

  auth: {
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Log in to manage your shop stamp card',
    signupTitle: 'Create Shop Account',
    signupSubtitle: 'Start rewarding loyal customers in minutes',
    emailLabel: 'Email address',
    emailPlaceholder: 'owner@cafe.com',
    passwordLabel: 'Password',
    passwordPlaceholder: 'At least 6 characters',
    loginButton: 'Log In',
    signupButton: 'Create Account',
    switchToSignup: "Don't have an account? Create one",
    switchToLogin: 'Already have an account? Log in',
    wrongPassword: 'Incorrect email or password. Please try again.',
    emailAlreadyUsed: 'An account with this email already exists.',
    invalidEmail: 'Please enter a valid email address.',
    passwordTooShort: 'Password must be at least 6 characters.',
    accountCreatedSuccess: 'Account created! Please check your email to confirm if required, or log in.',
    loggedInAs: 'Logged in as',
    logoutButton: 'Log Out',
    loggingIn: 'Logging in...',
    signingUp: 'Creating account...',
  },

  setup: {
    title: 'Setup Your Shop',
    subtitle: 'Enter your shop details to get started',
    shopNameLabel: 'Shop Name',
    shopNamePlaceholder: 'e.g. Chai Corner',
    stampsRequiredLabel: 'Stamps Needed for Free Reward',
    stampsRequiredHelper: 'Between 3 and 20 stamps (default is 8)',
    rewardTextLabel: 'Reward Text',
    rewardTextPlaceholder: 'e.g. Free chai, Free coffee, 10% off',
    saveShopButton: 'Create My Shop',
    nameEmptyError: 'Shop name cannot be empty.',
    rewardEmptyError: 'Reward description cannot be empty.',
    stampsRangeError: 'Stamps needed must be between 3 and 20.',
  },

  addStamp: {
    title: 'Add Stamp',
    phoneLabel: 'Customer Phone Number',
    phonePlaceholder: '050 123 4567',
    addStampButton: 'Add Stamp',
    addingStamp: 'Adding stamp...',
    stampAddedSuccess: 'Stamp added! {current} of {total}',
    cardFullTitle: 'Card is Full! 🎉',
    cardFullMessage: 'Customer has earned a reward: {reward}',
    giveRewardButton: 'Give Reward',
    givingReward: 'Giving reward...',
    rewardGivenSuccess: 'Reward given! Stamp count reset to 0.',
    tooSoonMessage: 'This customer got a stamp recently. Try again in {minutes} minutes.',
    invalidPhoneError: 'Please check the phone number.',
    undoButton: 'Undo last stamp ({seconds}s)',
    undoSuccess: 'Last stamp was removed.',
  },

  customers: {
    title: 'Customers',
    searchPlaceholder: 'Search by phone number...',
    totalCustomers: 'Customers',
    totalStamps: 'Stamps Given',
    totalRewards: 'Rewards Given',
    noCustomersFound: 'No customers found.',
    lastVisit: 'Last visit',
    neverVisited: 'Never',
    deleteCustomerTitle: 'Delete Customer',
    deleteCustomerConfirm: 'Are you sure you want to permanently delete this customer and all their stamp history?',
    deletedSuccess: 'Customer deleted.',
  },

  settings: {
    title: 'Settings',
    editShopTitle: 'Edit Shop Details',
    qrTitle: 'Customer QR Code',
    qrSubtitle: 'Customers scan this code to see their stamps on their phone (no app download needed).',
    customerPageLink: 'Customer Link',
    shareButton: 'Share / Print QR Code',
    privacyPolicy: 'Privacy Policy',
    logout: 'Log Out',
  },
};
