begin;

-- Roles are assigned by the project owner, never from editable user metadata.
create table public.content_staff (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('teacher', 'admin')),
  created_at timestamptz not null default now()
);
alter table public.content_staff enable row level security;
revoke all on public.content_staff from anon, authenticated;
grant select on public.content_staff to authenticated;
create policy staff_read_self on public.content_staff for select to authenticated
  using (user_id = (select auth.uid()));

create function public.is_content_staff() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.content_staff where user_id = (select auth.uid()));
$$;
revoke all on function public.is_content_staff() from public;
grant execute on function public.is_content_staff() to authenticated;

create table public.courses (
  id text primary key,
  title text not null check (length(trim(title)) > 0),
  target_language text not null,
  created_at timestamptz not null default now()
);
create table public.course_units (
  id text primary key,
  course_id text not null references public.courses(id),
  level text not null check (level in ('Pre-A1','A1','A2','B1','B2','C1')),
  title text not null check (length(trim(title)) > 0),
  position integer not null check (position > 0),
  unique (course_id, level, position)
);
create table public.lesson_drafts (
  id integer generated by default as identity (start with 1000000) primary key,
  unit_id text not null references public.course_units(id),
  content jsonb not null check (jsonb_typeof(content) = 'object'),
  revision integer not null default 1,
  updated_at timestamptz not null default now()
);
create table public.published_lessons (
  id integer primary key references public.lesson_drafts(id),
  unit_id text not null references public.course_units(id),
  content jsonb not null,
  revision integer not null,
  active boolean not null default true,
  published_by uuid references auth.users(id) on delete set null,
  published_at timestamptz not null default now()
);
create table public.lesson_publication_history (
  event_id bigint generated always as identity primary key,
  lesson_id integer not null references public.lesson_drafts(id),
  revision integer not null,
  action text not null check (action in ('publish', 'unpublish')),
  content jsonb not null,
  actor_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.courses enable row level security;
alter table public.course_units enable row level security;
alter table public.lesson_drafts enable row level security;
alter table public.published_lessons enable row level security;
alter table public.lesson_publication_history enable row level security;
revoke all on public.courses, public.course_units, public.lesson_drafts,
  public.published_lessons, public.lesson_publication_history from anon, authenticated;
grant select on public.courses, public.course_units, public.lesson_drafts,
  public.published_lessons, public.lesson_publication_history to authenticated;
grant insert, update on public.courses, public.course_units, public.lesson_drafts to authenticated;
grant usage on sequence public.lesson_drafts_id_seq to authenticated;

create policy courses_read on public.courses for select to authenticated using (true);
create policy courses_insert on public.courses for insert to authenticated with check (public.is_content_staff());
create policy courses_update on public.courses for update to authenticated using (public.is_content_staff()) with check (public.is_content_staff());
create policy units_read on public.course_units for select to authenticated using (true);
create policy units_insert on public.course_units for insert to authenticated with check (public.is_content_staff());
create policy units_update on public.course_units for update to authenticated using (public.is_content_staff()) with check (public.is_content_staff());
create policy drafts_read on public.lesson_drafts for select to authenticated using (public.is_content_staff());
create policy drafts_insert on public.lesson_drafts for insert to authenticated with check (public.is_content_staff());
create policy drafts_update on public.lesson_drafts for update to authenticated using (public.is_content_staff()) with check (public.is_content_staff());
create policy published_read on public.published_lessons for select to authenticated using (true);
create policy history_read on public.lesson_publication_history for select to authenticated using (public.is_content_staff());

create function public.bump_lesson_revision() returns trigger
language plpgsql set search_path = '' as $$
begin
  if tg_op = 'INSERT' then new.revision := 1;
  else new.revision := old.revision + 1; end if;
  new.updated_at := now();
  return new;
end;
$$;
create trigger lesson_revision before insert or update on public.lesson_drafts
for each row execute function public.bump_lesson_revision();

-- Lock the draft and check its revision so an older dashboard cannot publish
-- somebody else's concurrent edits. Learners cannot write published content.
create function public.publish_lesson(lesson_id integer, expected_revision integer)
returns void language plpgsql security definer set search_path = '' as $$
declare
  draft public.lesson_drafts;
  unit public.course_units;
  exercise jsonb;
begin
  if not public.is_content_staff() then raise exception 'Teacher access required' using errcode = '42501'; end if;
  select * into strict draft from public.lesson_drafts where id = lesson_id for update;
  if draft.revision <> expected_revision then raise exception 'Draft changed. Reload before publishing.'; end if;
  select * into strict unit from public.course_units where id = draft.unit_id;
  if jsonb_typeof(draft.content->'duration') is distinct from 'number'
    or jsonb_typeof(draft.content->'xp') is distinct from 'number'
    or jsonb_typeof(draft.content->'subtitle') is distinct from 'string'
    or jsonb_typeof(draft.content->'emoji') is distinct from 'string'
    or jsonb_typeof(draft.content->'color') is distinct from 'string' then
    raise exception 'Lesson display fields, duration and XP are required';
  end if;
  if (draft.content->>'duration')::numeric <= 0 or (draft.content->>'xp')::numeric < 0 then
    raise exception 'Duration must be positive and XP cannot be negative';
  end if;
  if coalesce(length(trim(draft.content->>'title')), 0) = 0
    or jsonb_typeof(draft.content->'exercises') is distinct from 'array' then
    raise exception 'A title and exercises are required';
  end if;
  if jsonb_array_length(draft.content->'exercises') = 0 then raise exception 'Add at least one exercise'; end if;
  for exercise in select value from jsonb_array_elements(draft.content->'exercises') loop
    if coalesce(length(trim(exercise->>'id')), 0) = 0
      or coalesce(length(trim(exercise->>'prompt')), 0) = 0
      or coalesce(exercise->>'type', '') not in ('learn','choice','build','speak','listen') then
      raise exception 'Each exercise needs an ID, prompt and supported type';
    end if;
    if exercise->>'type' in ('choice','build')
      and coalesce(length(trim(exercise->>'answer')), 0) = 0 then
      raise exception 'Scored exercises require an answer';
    end if;
    if exercise->>'type' in ('choice','build') then
      if jsonb_typeof(exercise->'options') is distinct from 'array' then raise exception 'Scored exercises require options'; end if;
      if jsonb_array_length(exercise->'options') = 0 then raise exception 'Add exercise options'; end if;
      if exercise->>'type' = 'choice' and not (exercise->'options' @> jsonb_build_array(exercise->>'answer')) then
        raise exception 'Answer must match a choice';
      end if;
    end if;
  end loop;
  if (select count(*) <> count(distinct value->>'id') from jsonb_array_elements(draft.content->'exercises')) then
    raise exception 'Exercise IDs must be unique';
  end if;
  draft.content := draft.content || jsonb_build_object('id', draft.id, 'unitId', draft.unit_id, 'level', unit.level);
  insert into public.published_lessons(id, unit_id, content, revision, published_by)
    values(draft.id, draft.unit_id, draft.content, draft.revision, auth.uid())
    on conflict (id) do update set unit_id = excluded.unit_id, content = excluded.content,
      revision = excluded.revision, active = true, published_by = excluded.published_by, published_at = now();
  insert into public.lesson_publication_history(lesson_id, revision, action, content, actor_id)
    values(draft.id, draft.revision, 'publish', draft.content, auth.uid());
end;
$$;

create function public.unpublish_lesson(lesson_id integer, expected_revision integer)
returns void language plpgsql security definer set search_path = '' as $$
declare published public.published_lessons;
begin
  if not public.is_content_staff() then raise exception 'Teacher access required' using errcode = '42501'; end if;
  perform 1 from public.lesson_drafts where id = lesson_id for update;
  select * into strict published from public.published_lessons where id = lesson_id;
  if published.revision <> expected_revision then raise exception 'Published version changed. Reload first.'; end if;
  insert into public.lesson_publication_history(lesson_id, revision, action, content, actor_id)
    values(lesson_id, published.revision, 'unpublish', published.content, auth.uid());
  -- Keep the previous public snapshot as a tombstone for bundled lesson IDs.
  update public.published_lessons set active = false where id = lesson_id;
end;
$$;
revoke all on function public.publish_lesson(integer,integer), public.unpublish_lesson(integer,integer) from public;
grant execute on function public.publish_lesson(integer,integer), public.unpublish_lesson(integer,integer) to authenticated;

commit;
